version: "3"

networks:
  inception:
    name: inception

services:
  NGINX:
    container_name: nginx
    image: nginx:42
    build: requirements/nginx/
    ports:
      - "443:80"
    networks:
      - inception
    env_file:
      - .env
    restart: always