version: "3"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/anaraujo/inception/srcs/requirements/wordpress
      o: bind
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/anaraujo/inception/srcs/requirements/mariadb
      o: bind
#The type of the mount, which can be bind, volume, or tmpfs. 

networks:
  inception:
    name: inception
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
    volumes:
      - wordpress:/var/www/html
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env
    restart: always
    volumes:
      - wordpress:/var/www/html
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    ports:
      - "3306:3306"
    networks:
      - inception
    env_file:
      - .env
    restart: always
    volumes:
      - mariadb:/var/lib/mysql/html

