version: "3"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/anaraujo/data/wordpress
      o: bind
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/anaraujo/data/mariadb
      o: bind
#The type of the mount, which can be bind, volume, or tmpfs. 

networks:
  inception:
    name: inception
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    restart: on-failure
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    expose: 
      - "9000"
    depends_on: 
      mariadb:
        condition: service_healthy
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
    volumes:
      - wordpress:/var/www/wordpress
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    expose: 
      - "3306"
    healthcheck:
      test: mysqladmin ping -h localhost -uroot -p${db_root_pwd}
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - inception
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql

