version: "3"

networks:
  inception:
    name: inception
    driver: bridge

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
    volumes:
      - wordpress:/var/www/html

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    networks:
      - inception
    env_file:
      - .env
    restart: always
    volumes:
      - wordpress:/var/www/html

volumes:
  wordpress:
#    name: wordpress
#    driver: local
#    driver_opts:
#      type: none
#      device: /home/anaraujo/Desktop/Inception/wordpress
#      o: bind
#The type of the mount, which can be bind, volume, or tmpfs. 
